### ISSUE TITLE
self.__cmd does not exist

### ISSUE THREAD

**Issue by KEggensperger** [mlindauer/GenericWrapper4AC#2]
When a solver returns a wrong model or UNSAT instead of SAT, satwrapper.py wants to store the failed call in a file, but self.__cmd does not exist as the target call is not stored in a variable.

AttributeError occurs here:
https://github.com/mlindauer/GenericWrapper4AC/blob/master/genericWrapper4AC/domain_specific/satwrapper.py#L83

and in line 120.

Question: Is this legacy code or do we want to store failed target algorithm calls?

**Comment by mlindauer** [comment]
Fixed -- removed legacy code
