### ISSUE TITLE
regex for parsing runsolver ouptut

### ISSUE THREAD

**Issue by YashaPushak** [mlindauer/GenericWrapper4AC#3]
I've realised the recent fix I suggested for parsing runsolver output contained a bug. I didn't realise that python only matched the '^'  character to the beginning of new lines when the flag re.MULTILINE is used.  As a result, my original 'fix' was causing the regex to never match, and wall clock time was being reported instead. I have verified that adding the re.MULTILINE flag does fix the problem, and the modified regex is now correctly matching the runsolver output for CPU time. 

Sorry I didn't catch my mistake sooner.

**Comment by mlindauer** [comment]
Thanks for posting this issue.

To be sure, you want to change it in the following way?

`cpu_pattern1 = re.compile('^runsolver_cputime: (%s)' % (self.float_regex()))`
-> 
` cpu_pattern1 = re.compile('^runsolver_cputime: (%s)' % (self.float_regex()), re.MULTILINE)`



Please consider submitting a pull request in the future, if you already have a solution for an issue.

Best,
Marius

**Comment by YashaPushak** [comment]
Yes, that should do the trick.

Cheers,
Yasha
